# Generated by Django 5.1.4 on 2024-12-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('SL', 'SALARY'), ('BS', 'BUISNESS'), ('FL', 'FREELANCE')], max_length=2),
        ),
    ]
